### ISSUE TITLE
✨  Simplestop Toggle

### ISSUE THREAD

**Issue by MitchellHayes** [tzfx/owrn#11]
Add the ability to toggle Simplestop on Pint & Pint X

**Comment by tzfx** [comment]
In implementing the custom shaping, I found out that the simplestop bt characteristic appears to be found as a subset of the ride trait characteristic:

```js
bleManagerEmitter.addListener(
          'BleManagerDidUpdateValueForCharacteristic',
          ({value, characteristic}) => {
            if (characteristic === CHARACTERISTICS.rideTrait) {
              const bTrait = Buffer.from(value);
              const [trait, traitValue] = [
                bTrait.readInt8(0),
                bTrait.readInt8(1),
              ];
              console.debug(`Read Trait !! ${trait}: ${traitValue}`);
              switch (trait) {
                // SNIP...
                case RIDE_TRAIT_VALUES.simpleStop: // 3
                  break;
                default:
                  console.error(
                    `Found invalid trait pair: ${[trait, traitValue].join(
                      ':',
                    )}`,
                  );
              }
            }
          },
        );
```

Read/write a 0 or a 1 there for enable/disable. Should be pretty easy-- however that listener is a bear since it fires off via BT notifications ALL THE TIME no real reason. I'd expect it to not notify if none of the characteristics have changed, but it appears that that's not the case.

It would be much nicer to read the characteristic/trait once and then re-read it as needed... but need to figure out how to read a (sub) trait once.
